### ISSUE TITLE
Auto Fight (Kill) not working.

### ISSUE THREAD

**Issue by hlorenz** [yzsvdu/RedTrainer#1]
Everything is working fine, except Auto-fight.

1. Char is walking is circle (work)
2. Enemy appears - I got 4 options (fight, item, pokemon, flee) and here the bot stop working, until I press manually "fight". After that, the bot is Using my setted Combat skill and everything is fine.

But it stops everytime on the UI, where I can select "fight" "Pokemon" "Item" and "Flee"

Using Windows, JDK17, and German Pokemon UI (maybe I need englisch pokemon UI/Roms?)

**Comment by yzsvdu** [comment]
The problem is having the UI as German. 
This is because as of right now, the bot looks for the button with label "FIGHT". 
Soon I will release an update that will fix that issue. Thanks for the report!

**Comment by yzsvdu** [comment]
https://github.com/yzsvdu/RedTrainer/releases/tag/v1.1.1

**Comment by hlorenz** [comment]
Super Fast Fixing. Now, It works fine! Looking forward to new Releases :)
