### ISSUE TITLE
stuck at attempting to connect to server

### ISSUE THREAD

**Issue by tannmay-python** [yzsvdu/RedTrainer#5]
<img width="567" alt="image" src="https://github.com/user-attachments/assets/ab27bad0-541c-4550-8bec-58f2d08dbdff">

I'm stuck here. A little new to java programming, usually code python. Please do help me out, what am I doing wrong?

**Comment by hlorenz** [comment]
I also had problems to run that on mac. Well, I managed to start as following:

- Starting Terminal
**- Change in your terminal the current directory to the main directory where the jar and sh is located (cd ...)** (!!!!)
- and then execute the start file within ur terminal...

How ever, I wasnt able to run the main jar file. I had a "**critical render error**". I assume, that my processor is not supporting that...... Im using macbook pro 2016 (Intel I7)

**Comment by tannmay-python** [comment]
My directory is the /pokemmo-client-live

**Comment by tannmay-python** [comment]
could the issue be because i'm using an intel mac as well? is this script only for arm64 macs?

**Comment by tannmay-python** [comment]
just for clarity i am getting the window but its just not connecting to the pokemmo server

![Uploading image.png…]()

**Comment by yzsvdu** [comment]
Hi you are in the pokemmo directory and ran ./mac_start.sh and then in another tab java -jar client.jar?

**Comment by tannmay-python** [comment]
Yes

**Comment by tannmay-python** [comment]
java -jar client.jar was giving me an error 
<img width="1789" alt="image" src="https://github.com/user-attachments/assets/4dff6d51-f4cd-4671-ac8b-9bb6b3c9330b">

So i used java --module-path /Users/tannmaybaid/Downloads/javafx-sdk-17.0.12\ /lib --add-modules javafx.controls,javafx.fxml -jar client.jar

**Comment by yzsvdu** [comment]
Not sure of a fix since i dont have an intel mac but maybe try clean reinstalling java 17.

**Comment by tannmay-python** [comment]
Or maybe i'll bootcamp xD

**Comment by yzsvdu** [comment]
I've open sourced the client code so you can try building it for yourself on intel mac.
