### ISSUE TITLE
Error loading PokeMMO data package. The current data may be invalid or corrupt. 

### ISSUE THREAD

**Issue by PatrickJnr** [yzsvdu/RedTrainer#9]
I always seem to be getting, even after a repair.

```
Error loading PokeMMO data package.
The current data may be invalid or corrupt.
Please reinstall the client to resolve this issue.

Do you want to attempt to repair your PokeMMO client?
```

![image](https://github.com/user-attachments/assets/62eb5f38-7963-48b1-a3f3-60c62507c859)

**Comment by yzsvdu** [comment]
Hi, the bot is not updated for the latest update so it starts up the older version of the game which is why you see the error.

**Comment by PatrickJnr** [comment]
That makes sense, thank you!
